name: A workflow for my Hello World file
on:
  push:
    branches: # Array of patterns that match refs/heads
      - master

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/action-a
        env:
          MY_NAME: "Luca"
